### ISSUE TITLE
Servo1D toggleGripper

### ISSUE THREAD

**Issue by dwheatle** [FRC8167/Into-The-Deep#3]
Since this class was originally developed for the gripper, the toggle function made sense here.  Since abstracting the class to handle multiple sub systems.  This function needs to be rewritten not using gripper constants.  Either two values need to be passed in to the constructor and saved as class variables or passed directly into the toggle function.  

Alternatively,  a gripper sub system can be created that extends Servo1D and contains the toggle function.   
 
https://github.com/FRC8167/Into-The-Deep/blob/564d05152be6905fe423bf596585576776c31984/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SubSytems/Servo1D.java#L27-L39

**Comment by FRC8167** [comment]
@laurenktn Created a child class which now performs this function.
